### ISSUE TITLE
Change radius of RoundedRectangle shader with animation

### ISSUE THREAD

**Issue by AndriyShpyra** [rdkcentral/Lightning#183] opened 2020-05-23 16:12 UTC
Is it possible to dynamically change the RoundedRectangle shader radius?
For instance, on  _focus action, the radius is increasing with animation, and on _unfocus it returns to its previous size.

**Comment by jhderojasUVa** [comment] 2020-05-23 16:29
You can do it with a .patch and changing the property on "run time".

Jesus Hernandez de Rojas
jhderojas@gmail.com

http://macadas.no-ip.info
http://twitter.com/tuti (personal)
http://twitter.com/jhderojas (profesional)

**Comment by g-zachar** [comment] 2020-05-25 07:30
Duplicate of #123

**Closed by g-zachar** 2020-05-25 07:30 UTC

**Comment by mattiapontonio** [comment] 2020-05-25 07:49
@jhderojasUVa can You please explain? There is a way to "bind things to patch"?

**Comment by jhderojasUVa** [comment] 2020-05-25 09:18
The most easy way is seen an example:

`export default class App extends Lightning.Component {

  static _template() {
    return {
      Background: {
        w: 1920,
        h: 1080,
        color: 0xFFffffff,
        rect: true,
      },
      BoxWithShadow_1: {
        x: 100,
        y: 100,
        type: ShadowBox
      },
      BoxWithShadow_2: {
        x: 400,
        y: 100,
        type: ShadowBox
      },
    }
  }

  static _states() {
    return [
      class FocusLeft extends this {
        _getFocused() {
          return this.tag('BoxWithShadow_1');
        }
      },
      class FocusRight extends this {
        _getFocused() {
          return this.tag('BoxWithShadow_2');
        }
      }
    ]
  }

  _handleLeft() {
    this._setState('FocusLeft');
  }

  _handleRight() {
    this._setState('FocusRight');
  }

  _init() {
    console.log('App starting!');
  }

  _getFocus() {
    return this;
  }

}

class ShadowBox extends Lightning.Component {
  static _template() {
    return {
      Box: {
        x: 0,
        y: 0,
        w: 150,
        h: 40,
        zIndex: 2,
        color: 0xFFff0000,
        rect: true
      },
      Shadow: {
        x: 10,
        y: 10,
        zIndex: 1,
        color: 0x66000000,
        texture: lng.Tools.getShadowRect(150, 40, 4, 10, 15),
      }
    }
  }

  _focus() {
    this.tag('Shadow').patch({
      texture: lng.Tools.getShadowRect(150, 40, 4, 10, 15)
    });
  }

  _unfocus() {
    this.tag('Shadow').patch({
      texture: lng.Tools.getShadowRect(150, 40, 10, 20, 50)
    });
  }

  _init() {
    console.log('BoxShadow started!');
  }
}
`

You will see that I have create an small App that contains two objects that have a shadow and some states for "selecting" one or another. When one of the objects type ShadowBox is focused I patch the object with a new values on the texture property of the object and, when it's de-focused, I do it again (on the previous values, of couse).

With .patch you can change the properties of an object "in runtime", so it's great to make use of it  https://rdkcentral.github.io/Lightning/docs/renderEngine/patching

**Comment by mattiapontonio** [comment] 2020-05-25 09:46
@jhderojasUVa ok thanks. But [here's](https://github.com/rdkcentral/Lightning/issues/183#issue-623691376) talking about `animation / transition` so the `smooth` part of the patch object. Is possible to create a texture that patches smoothly?

**Comment by jhderojasUVa** [comment] 2020-05-25 10:32
Yes, you can do it with a for and a timeout... you must adjust the values :)

It's not pretty but works

```
_focus() {
    this.alpha = 0.5;
    
    for(let i = 10; i <= 20; i = i + 2) {
      setTimeout(() => {
        this.tag('Shadow').patch({
          texture: lng.Tools.getShadowRect(150, 40, 4, i, 15)
        });
        
      }, 1000 * i/10);
    }
  }
```

**Comment by mattiapontonio** [comment] 2020-05-25 11:27
@jhderojasUVa should be better if You can "subscribe" in some way to the same callback of the `patch`.

**Comment by jhderojasUVa** [comment] 2020-05-25 11:53
You can create or use an emitter so you can cancel or know the moment of the patch if that's you want to do for control in a better way the "effect"

**Comment by mattiapontonio** [comment] 2020-05-25 12:24
I do not know the complexity of this but I think a good way is to move the "`border-radius`" property from a `Tools` to `Component` template so it can use the same engineering of the others property transitions.

**Comment by jhderojasUVa** [comment] 2020-05-25 14:00
As far I know the border radius is done by a gl shader, so it's more complex inside that "moving the tool". In fact I had tried to create a new shader with time transition and seems very complicated.

**Comment by g-zachar** [comment] 2020-05-25 14:04
Guys, I'm not sure if you missed it but I linked to ongoing issue #123 , which also has the example that should help your case ([direct link](https://jsfiddle.net/rgsdhcy9/)). If it's not, please continue discussion there.

Best regards
