### ISSUE TITLE
maxLinesSuffix is cutted when advancedRender = true

### ISSUE THREAD

**Issue by KaterynaHryhorenko** [rdkcentral/Lightning#429] opened 2022-11-03 08:06 UTC
Hi Lightning team,

Is it expected that in advancedRenderer mode maxLineSuffix will be corrupted?

**Example**

![Screenshot 2022-11-03 101856](https://user-images.githubusercontent.com/43144910/199674382-c1047244-dd02-4031-acd4-b62b44b0f1f5.png)

```{js}
Quote: {
        text: {
          textColor: '#ffffffff',
          maxLines: 2,
          wordWrapWidth: 1000,
          textOverflow: 'ellipsis',
          maxLinesSuffix: '... <b>End of text</b>',
          advancedRenderer: true,
          text: "Humanity takes itself too seriously. It is the world's original sin. If the cave-man had known how to laugh, History would have been different",
        },
      },
```

**Comment by g-zachar** [comment] 2022-11-05 17:10
Hi @KaterynaHryhorenko 

thanks for reporting, this is indeed unintended behavior. Should be fixed in the next release.

Best regards

**Closed** 2023-02-16 12:03 UTC
Labels: bug
