### ISSUE TITLE
High GFX memory usage when switching between metro lightning apps

### ISSUE THREAD

**Issue by jacek-skiba-red** [rdkcentral/Lightning#369] opened 2022-02-09 12:29 UTC
During navigation between Metro Lightning applications we see increased GFX memory usage:
* metro boot URL
* CNN app
* metro boot URL
* Euronews
* metro boot URL
* Deezer

Boot URL in that scenario holds many MB (100-200 MB) of graphics memory, where page is not rendering anything (page don't have <video> or <canvas> tag). When we are on boot URL that graphics memory cannot be used by box UI application (which is not browser based in our middleware).

Problem is seen when Lightning framework is using WebGL or Canvas API for rendering.
Problem disappears when we load any non-metro application or we force to reload metro app.

Forcing garage collector API is not releasing that memory:
curl -d '{"method": "WebKitBrowser.1.collectgarbage"}' http://127.0.0.1:9998/jsonrpc

We monitor graphcs memory usage with /proc filesystem which is managed by nexus: /proc/brcm/core (GFX row).

We think that this is a Lightning framework issue, because problem was also reproduced on Chrome on Linux: https://drive.google.com/file/d/1IL9saORCizOYr_EC1AFFRH2c6srp3Zr2/view

**Comment by rychem** [comment] 2022-02-10 11:13
@woutermeek issue mirrorred from RDK-509

**Comment by michielvandergeest** [comment] 2022-02-14 20:25
The issue described seems to be specific to loading and unloading apps in the context of the Metrological App Store.

We haven't seen similar memory issues with pure Lightning apps, so this might actually have something to do with the app switching mechanism (which is a specific functionality of the _Metro App Store_) which is retaining memory, or not managing to properly clean up JS resources. It can also be the specific apps not cleaning up properly (i.e. holding on to timers and intervals).

It seems appropriate for this to be investigated on the Metro platform side first. I've gone ahead and copied this issue into a ticket on the internal Metrological Jira, assigned to @oscaruitenbroek so it can be handled further there

**Closed by michielvandergeest** 2022-02-14 20:25 UTC

**Comment by jacek-skiba-red** [comment] 2022-02-17 13:56
Root cause of this memory leak is related to not garbage collected HTMLCanvasElement. I provided few examples:
* https://drive.google.com/file/d/1sJEHWX_uFBl_SRFFaRcPx0WWhznJ5wES/view?usp=sharing : dummy test page which is creating/removing on demand canvas tag. Constructors and destructors are correctly called
 
* https://drive.google.com/file/d/1coGQauhjOkiN21adTk4wlgoHL37tpxMw/view?usp=sharing : googe webgl test page. Constructors and destructors are correctly called
 
* https://drive.google.com/file/d/11QVBAGc13L3WUakNQ4oUjx2akFY8tlKN/view?usp=sharing: on lightning app on boot URL we still have one canvas element which is not released. Hoever, we don't see any canvas tag in DOM tree.
 
Issue was seen on all lightning based apps (including VRT NU - which was developed not by Metro).
We have interesting results from strike framework:
issue was visible on tests : plains / trains
issue was NOT visible on tests : images / text
 
 Forcing about:blank or reloading page is removing all canvas objects by Garbage collector from memory.

**Comment by rychem** [comment] 2022-02-17 15:53
@michielvandergeest 
I believe this issue should be tracked still here ( as agreed with @woutermeek ). Even if investigation is continued by Metro platform team lets keep progress documented in one place. There is no other repo dedicated to metro platform, internal Metrological jira has only internal access. 
Let me suggest reopening this issue.

**Comment by michielvandergeest** [comment] 2022-02-21 13:31
It looks pretty obvious there is a memory leak going on here. We can agree on that :) The question is just whether the leak is caused by the Lightning framework, or if it's a memory leak caused by the App code or by the Metro store responsible for launching and app switching.

I've done some tests and I'm convinced the later is the case (i.e. it's the metro store that is retaining the references and thus preventing the browser from doing proper garbage collection).

I will provide my finding to the Metrological platform team, so they can take it from there. I just want to stress that it _doesn't_ look like an issue caused by Lightning. @rychem that's why we also don't think it's appropriate to keep the ticket open here, as it may send off the wrong message about the Lightning framework itself.

@jacek-skiba-red wrt your findings about Strike: I checked the code and it seems like you've stumbled upon a potential memory leak in the _App_ code (again, not the Lightning framework code). The trains page contained an interval that was not properly being cleaned up upon exit (one of the primary causes for memory leaks). Thanks for this find :) ... we'll publish a new fixed version of Strike this week.
